syntax = "proto3";

package dashboard.services.v1;

option go_package = "github.com/MediStatTech/dashboard-client/pb/go/services/v1";

import "google/protobuf/timestamp.proto";
import "models/v1/patient_dash.proto";

service PatientService {
  rpc PatientGet(PatientGetRequest) returns (PatientGetReply);
  rpc PatientRetrieve(PatientRetrieveRequest) returns (PatientRetrieveReply);
  rpc PatientCreate(PatientCreateRequest) returns (PatientCreateReply);
  rpc PatientPanicTrigger(PatientPanicTriggerRequest) returns (PatientPanicTriggerReply);
}

message PatientGetRequest {}

message PatientGetReply {
  repeated dashboard.models.v1.Patient.ListItem patients = 1;
}

message PatientRetrieveRequest {
  string patient_id = 1;
}

message PatientRetrieveReply {
  dashboard.models.v1.Patient.Read patient = 1;
}

message PatientCreateRequest {
  dashboard.models.v1.Patient.Create patient = 1;
}

message PatientCreateReply {
  dashboard.models.v1.Patient.Read patient = 1;
}

message PatientPanicTriggerRequest {
  string patient_id       = 1;
  int32  duration_seconds = 2;
}

message PatientPanicTriggerReply {
  google.protobuf.Timestamp panic_until = 1;
}
